from pyspark.sql.types import (ArrayType, BinaryType, DoubleType, StructType,
                               StructField, StringType, IntegerType, LongType)

ARCHIVE_ORG_SCHEMA = StructType([
    StructField("created", LongType(), True),
    StructField(
        "files",
        ArrayType(
            StructType([
                StructField("bitrate", StringType(), True),
                StructField("format", StringType(), True),
                StructField("height", StringType(), True),
                StructField("length", StringType(), True),
                StructField("name", StringType(), True),
                StructField("original", StringType(), True),
                StructField("size", StringType(), True),
                StructField("source", StringType(), True),
                StructField("title", StringType(), True),
                StructField("track", StringType(), True),
              # Strangely, choosing "BooleanType()" for "private" makes all of the rows "null".
                StructField("private", StringType(), True)
            ]), True),
        True),
    StructField("identifier", StringType(), True),
    StructField(
        "metadata",
        StructType([
            StructField("Length", StringType(), True),
            StructField("addeddate", StringType(), True),
            StructField("adder", StringType(), True),
            StructField("aspect_ratio", StringType(), True),
            StructField("backup_location", StringType(), True),
            StructField("closed_captioning", StringType(), True),
            StructField("collection", StringType(), True),
            StructField("color", StringType(), True),
            StructField("contact", StringType(), True),
            StructField("coverage", StringType(), True),
            StructField("creator", StringType(), True),
            StructField("credits", StringType(), True),
            StructField("curation", StringType(), True),
            StructField("date", StringType(), True),
            StructField("description", StringType(), True),
            StructField("director", StringType(), True),
            StructField("duration", StringType(), True),
            StructField("format", StringType(), True),
            StructField("genre", StringType(), True),
            StructField("glob", StringType(), True),
            StructField("holder", StringType(), True),
            StructField("identifier", StringType(), True),
            StructField("identifier-access", StringType(), True),
            StructField("identifier-ark", StringType(), True),
            StructField("imdb", StringType(), True),
            StructField("keywords", StringType(), True),
            StructField("language", StringType(), True),
            StructField("license", StringType(), True),
            StructField("licenseurl", StringType(), True),
            StructField("mediatype", StringType(), True),
            StructField("pbcore-genre", StringType(), True),
            StructField("pick", StringType(), True),
            StructField("presenter", StringType(), True),
            StructField("producer", StringType(), True),
            StructField("publicdate", StringType(), True),
            StructField("publisher", StringType(), True),
            StructField("release_date", StringType(), True),
            StructField("repub_state", StringType(), True),
            StructField("resource", StringType(), True),
            StructField("runtime", StringType(), True),
            StructField("subject", StringType(), True),
            StructField("title", StringType(), True),
            StructField("tv-parental-guidelines", StringType(), True),
            StructField("updatedate", StringType(), True),
            StructField("updater", StringType(), True),
            StructField("upload_application", StringType(), True),
            StructField("uploader", StringType(), True),
            StructField("year", StringType(), True),
        ]), True),
])
